version: 2.1

executors:
  node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/project

commands:
  build:
    description: "Builds project"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: load environment variables
          command: sh ./scripts/deploy_config.sh
      - run:
          name: Build for current environment.
          command: npm run prerender
  deploy:
    description: "Deploy project to the designated environment"
    parameters:
      env:
        type: string
        default: "develop"
    steps:
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting:<< parameters.env >> --non-interactive 

jobs:
  build-deploy-develop:
    executor: node10
    steps:
      - build
      - deploy: 
          env: "develop"
  build-deploy-production:
    executor: node10
    steps:
      - build
      - deploy:
          env: "production"

workflows:
  version: 2
  develop:
    jobs:
      - build-deploy-develop:
          filters:
            branches:
              only: develop
  production:
    jobs:
      - build-deploy-production:
          filters:
            branches:
              only: master